# Rockchip RK3399 hexa core 2-4GB SoC GBE FE eMMC USB3 PCIe
BOARD_NAME="MPC1903"
BOARDFAMILY="rockchip64"
BOOTCONFIG="mpc1903-rk3399_defconfig"
KERNEL_TARGET="current"
FULL_DESKTOP="yes"
BOOT_LOGO="desktop"
BOOT_FDT_FILE="rockchip/rk3399-mpc1903.dtb"
BOOT_SUPPORT_SPI=yes
FULL_DESKTOP="yes"
BOOT_LOGO="desktop"
SRC_EXTLINUX="yes"
SRC_CMDLINE="console=ttyS2,1500000 console=tty0"
BOOT_SCENARIO="tpl-spl-blob"
BOOT_SUPPORT_SPI=yes
